services:
  db:
    container_name: postgres-todo
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo

  redis:
    container_name: redis-todo
    image: redis:7.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - todo

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redis-insight:/data
    networks:
      - todo

volumes:
  postgres_data:
  redis_data:
  redis-insight:

networks:
  todo:
